[build]
  publish = "lifecure-medicos"

[[redirects]]
  from = "/admin"
  to   = "/admin.html"
  status = 200

[[redirects]]
  from = "/login"
  to   = "/login.html"
  status = 200

[[redirects]]
  from = "/signup"
  to   = "/signup.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to   = "/dashboard.html"
  status = 200